from src.db.schema import GAMES_META_SCHEMA, TEAMS_SCHEMA, PLAYERS_SCHEMA, PLAYER_STATS_SCHEMA, GAME_STATS_SCHEMA, \
    GAME_ODDS_SPREAD_SCHEMA, GAME_ODDS_ML_SCHEMA, PLAYER_PROP_ODDS_SCHEMA, PLAYER_PROP_RESULTS_SCHEMA, \
    GAME_ODDS_ML_RESULTS_SCHEMA

SCHEMAS = [
    GAMES_META_SCHEMA,
    TEAMS_SCHEMA,
    PLAYERS_SCHEMA,
    PLAYER_STATS_SCHEMA,
    GAME_STATS_SCHEMA
]

ODDS_SCHEMAS = [
    PLAYER_PROP_ODDS_SCHEMA,
    GAME_ODDS_SPREAD_SCHEMA,
    GAME_ODDS_ML_SCHEMA
]

ODDS_RESULTS = [
    PLAYER_PROP_RESULTS_SCHEMA,
    GAME_ODDS_ML_RESULTS_SCHEMA
]
