from src.db.schema import GAMES_META_SCHEMA, TEAMS_SCHEMA, PLAYERS_SCHEMA, PLAYER_STATS_SCHEMA, GAME_STATS_SCHEMA

SCHEMAS = [
    GAMES_META_SCHEMA,
    TEAMS_SCHEMA,
    PLAYERS_SCHEMA,
    PLAYER_STATS_SCHEMA,
    GAME_STATS_SCHEMA
]